package demo.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import demo.model.UserAccount;
import demo.model.UserAccountExample;

public interface UserAccountRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    long countByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int deleteByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    List<UserAccount> selectByExample(UserAccountExample example);
    List<UserAccount> selectByExample();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    UserAccount selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useraccount
     *
     * @mbg.generated Thu Jun 18 08:08:29 JST 2020
     */
    int updateByPrimaryKey(UserAccount record);
}