package demo.model;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.user_id
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.user_name
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.user_id
	 * @return  the value of account.user_id
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.user_id
	 * @param userId  the value for account.user_id
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.user_name
	 * @return  the value of account.user_name
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.user_name
	 * @param userName  the value for account.user_name
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
	 * @return  the value of account.password
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
	 * @param password  the value for account.password
	 * @mbg.generated  Mon Jun 15 16:48:12 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
}